services:
  timescaledb:
    image: timescale/timescaledb:latest-pg15
    ports:
      - 5432:5432/tcp
    environment:
      - POSTGRES_USER=timescaledb
      - POSTGRES_PASSWORD=timescaledb
      - POSTGRES_DB=timescaledb
