name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pytest:

    runs-on: ubuntu-latest
    env:
      PDM_BUILD_SCM_VERSION: "1.0.0"
    services:
      timescaledb:
        image: timescale/timescaledb:latest-pg15
        env:
          POSTGRES_PASSWORD: timescaledb
          POSTGRES_USER: timescaledb
          POSTGRES_DB: timescaledb
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - uses: pdm-project/setup-pdm@v3
    - name: Install dependencies
      run: |
        pdm sync
    - name: Run tests
      run: |
        pdm run pytest
