name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pytest:
    name: Run linting and tests

    runs-on: ubuntu-latest
    env:
      PDM_BUILD_SCM_VERSION: "1.0.0"
    services:
      timescaledb:
        image: timescale/timescaledb:latest-pg15
        env:
          POSTGRES_PASSWORD: timescaledb
          POSTGRES_USER: timescaledb
          POSTGRES_DB: timescaledb
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - uses: pre-commit/action@v3.0.0
      with:
        extra_args: --all-files --show-diff-on-failure

    - uses: pdm-project/setup-pdm@v3

    - name: Install dependencies
      run: pdm install -x --no-editable -dG test

    - name: Run tests
      run: pdm run pytest -v --cov=dbt --cov-report=xml -n auto tests/

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      with:
        files: ./coverage.xml
